management/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    #url(r'^check/$', views.check),
    #url(r'^xlsx/$', views.xlxs_try),
    #url(r'^user_xlsx/$', views.user_xlsx,name='user_xlsx'),
    url(r'^add-student-db/$', views.student_db_add,name='student_db'),
    url(r'^update-student-db/$', views.student_db_update,name='student_db_update'),
    url(r'^$', views.home, name= 'm_home' ),
    #url(r'^trial/$', views.trial,),
    url(r'^add_user/$', views.add_user, name= 'add_user' ),
    url(r'^download_resume/$', views.get_resume_zip, name= 'r_downloader' ),
    url(r'^add_manager/$', views.create_manager, name= 'add_manager' ),
    url(r'^add_company/$', views.add_company, name= 'add_company' ),
    url(r'^login/$', auth_views.login, {'template_name': 'new/login.html', 'extra_context':{'log_nav_active':'active'}}, name='login'),
    url(r'^logout/$',auth_views.logout, {'next_page': 'management:login'}, name = 'logout'),
    url(r'^mod_pass/$', views.changepass, name= 'mod_pass' ),
    url(r'^search_company/$', views.search_company, name= 'search_company' ), 
    url(r'^search_user/$', views.search_user_extended, name= 'search_user' ), 
    url(r'^view-reg/$', views.view_registrations, name= 'view_reg' ),
    url(r'^view-reg-2/$', views.view_registrations_new, name= 'view_reg_new' ),
    url(r'^edit_company/(?P<id>[\d]+)/$', views.edit_company, name= 'edit_company' ),
    url(r'^search_company/(?P<field_type>[a-z]{4})/(?P<slug>[-\w+]+)/$', views.search_company, name= 'search_company_result' ),    
    url(r'^search_user/(?P<field_type>[_\w+]+)/(?P<slug>[-\w\s+]+)/$', views.search_user, name= 'search_user_result' ),    
    url(r'^view-reg/(?P<slug>[-\w\s+]+)/(?P<f_choice>[-\w\s+]+)/$', views.view_registrations, name= 'view_reg_search' ),    
    url(r'^view-reg-2/(?P<slug>[-\w\s+]+)/(?P<f_choice>[-\w\s+]+)/$', views.view_registrations_new, name= 'view_reg_search_new' ),
    url(r'^add-placement/$', views.add_placement_ajax, name= 'add_placement' ),
    url(r'^add-ppo/$', views.add_ppo_view, name= 'add_ppo' ),
    url(r'^get-ajax/$', views.load_user, name= 'ajax_user' ),
    url(r'^ban/$', views.ban_select, name= 'ban_select' ),
    url(r'^batch-email/$', views.batch_email_view, name= 'batch_emails' ),
    url(r'^send-sms/$', views.send_sms_view, name= 'send_sms' ),
    url(r'^batch-email-get-email-ajax/$', views.get_email_address_list, name= 'batch_email_get_email_ajax' ),
    url(r'^batch-email-boto-call-ajax/$', views.send_mail_boto_call_ajax, name= 'email_boto_call_ajax' ),
    url(r'^get-rej-ajax/$', views.get_registration_ajax, name= 'get_reg_ajax' ),
    url(r'^batch-email-template-preview-ajax/$', views.batch_email_template_preview_ajax, name= 'get_email_preview_ajax' ),
    url(r'^batch-email-select-ajax/$', views.batch_email_select_ajax, name= 'get_select_ajax' ),
    url(r'^ban/(?P<roll_no>[0-9]{1,4}[a-zA-Z]{1,5}[0-9]{1,4})/$', views.ban_proceed, name= 'ban_proceed' ),
    url(r'^revoke-ban/(?P<roll_no>[0-9]{1,4}[a-zA-Z]{1,5}[0-9]{1,4})/$', views.revoke_ban, name= 'revoke_ban' ),
    url(r'^modify-user/(?P<uid>[0-9]{1,20})/$', views.modify_user, name= 'modify_user' ),
    #url(r'^company_search/(?P<field_type>[a-z]{4})/(?P<slug>[-\w]+)')
    #This py file developed by Yash Kulshreshtha
#visit https://fb.com/yksmbkkr
    ]

tnp/urls.py
"""
Definition of urls for tnp.
"""

from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from management import views as m_views
from student import views as s_views
from django.conf.urls import handler404, handler500
from . import views


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', tnp.views.home, name='home'),
    # url(r'^tnp/', include('tnp.tnp.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^ps-r558u/', include(admin.site.urls)),
    url(r'^management/',include('management.urls', namespace='management')),
    url(r'^',include('student.urls', namespace='student')),
    #url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'password_reset_form.html', 'email_template_name':'password_reset_email.html','subject_template_name':'password_reset_subject.txt','extra_context':{'pswd_nav_active':'active color-change'}}, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name':'password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name':'password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, {'template_name':'password_reset_complete.html'}, name='password_reset_complete'),
   #url(r'^su/$', m_views.search_user_extended),
    #url(r'^mdc/$', s_views.mdc),
]

handler404 = views.error_404
handler500 = views.error_500
admin.site.site_header = "TNP Admin Portal"
admin.site.site_title = "TNP Admin Portal"
admin.site.index_title = "Welcome to TNP Admin Portal"

management/models.py
from django.db import models
from django.contrib.auth.models import User

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

# Create your models here.
#This py file developed by Yash Kulshreshtha
#visit https://fb.com/yksmbkkr

def validate_batch_name(name):
    if not str(name) in ['Internship', 'Placement']:
         raise ValidationError(
            _('Name can either be "Placement" or "Internship"'),
        )

class current_batch_year(models.Model):
    year = models.PositiveIntegerField()
    name = models.CharField(max_length = 20)

    def clean(self, *args, **kwargs):
        if current_batch_year.objects.all().count() > 1 :
            raise ValidationError(
            _('There can not be more than 2 entries in this table. It already contains 2 so you can not add more.'),
        )
        str1 = self.name
        if not str(str1) in ['Internship', 'Placement']:
            raise ValidationError(
            _('Name can either be "Placement" or "Internship"'),
        )
        super(current_batch_year, self).clean(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.full_clean()
        super(current_batch_year, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class profile_set(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key = True)
    check = models.BooleanField(default = False)
    def __str__(self):
        return self.user.get_username()

class user_info(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key = True)
    be_marks = models.CharField(max_length = 5)

class managers(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key = True)
    email = models.EmailField(unique = True)
    creation = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.get_username()

class branch_type(models.Model):
    name = models.CharField(max_length=10, unique=True)
    def __str__(self):
        return self.name


class branches(models.Model):
    code = models.CharField(max_length = 3, unique = True)
    name = models.CharField(max_length = 5, unique=True)
    branchType = models.ForeignKey(branch_type, on_delete=models.CASCADE)
    def __str__(self):
        return self.name



class company_grade(models.Model):
    grade = models.IntegerField(primary_key=True)
    grade_name = models.CharField(unique = True, max_length = 10)
    def __str__(self):
        return self.grade_name

class company(models.Model):
    name = models.CharField(max_length = 50)
    for_batch = models.ForeignKey(current_batch_year, on_delete=models.CASCADE)
    slug_name = models.CharField(max_length = 70, null = True)
    ctc = models.IntegerField(default = 0)
    grade = models.ForeignKey(company_grade,on_delete = models.CASCADE)
    cutoff = models.DecimalField(max_digits=5,decimal_places=2, verbose_name = "Cut-off")
    branch_allowed = models.ManyToManyField(branches,db_table="branchElligibleForCompany")
    backlogs_allowed = models.IntegerField()
    closing_date = models.DateField()
    cap = models.IntegerField(default = -1,blank = False)
    open_reg = models.BooleanField(default = True)
    creation = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        if self.for_batch is None:
            return self.name
        return self.name + " ( "+self.for_batch.name+" )"

    class Meta:
        ordering = ['name']

class student_email_db(models.Model):
    rollno = models.CharField(max_length = 20, unique = True,primary_key = True)
    email = models.CharField(max_length = 150, unique = True)
    cgpa = models.CharField(max_length = 150,default = '0')
    backlog = models.CharField(max_length=10,default = '0')
    sem1 = models.CharField(max_length = 15,default = '0')
    sem2 = models.CharField(max_length = 15,default = '0')
    sem3 = models.CharField(max_length = 15,default = '0')
    sem4 = models.CharField(max_length = 15,default = '0')
    sem5 = models.CharField(max_length = 15,default = '0')
    sem6 = models.CharField(max_length = 15,default = '0')
    batch = models.CharField(max_length = 15, default = '2020')
    def __str__(self):
        return self.rollno

class ban(models.Model):
    rollno = models.CharField(max_length = 20, unique = True)
    till_date = models.DateField(null = True)
    companies = models.ManyToManyField(company,db_table="bannedInCompany",blank=True)
    company_count = models.IntegerField(default = 0)
    banned_by = models.ForeignKey(User,on_delete = models.PROTECT)
    banned_on = models.DateTimeField()
    def __str__(self):
        return self.rollno

class sms_logs(models.Model):
    sender = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    receiver = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='sms_logs_receiver')
    message_body = models.CharField(max_length=200)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sender.username+' - '+self.receiver.username

management/templates/add_company.html
{%extends 'skeleton.html'%}

{%block body%}

<div class="bootstrap-iso">
            <div class="container-fluid">
              <div class="row">
                  {%if form.errors%}
{%for field in form%}
<ul>
    {%for error in field.errors%}
    <li>{{field.name}} : {{error}}</li>
    {%endfor%}
</ul> 
{%endfor%}
{%endif%}
{%if messages%}
{%for message in messages%}
{{message}}
{%endfor%}
{%endif%}
               <div class="col-md-6 col-sm-6 col-xs-12">
                <form class="form-horizontal" method="post">
                 <div class="form-group ">
                  <label class="control-label col-sm-2" for="CompanyName">
                   Company Name
                  </label>
                  <div class="col-sm-10">
                   {{form.name}}
                  </div>
                 </div>
                     <div class="form-group ">
                  <label class="control-label col-sm-2" for="Grade">
                   For Batch
                  </label>
                  <div class="col-sm-10">
                   {{form.for_batch}}
                  </div>
                 </div>
                    <div class="form-group ">
                  <label class="control-label col-sm-2" for="ctc">
                   CTC
                  </label>
                  <div class="col-sm-10">
                   {{form.ctc}}
                  </div>
                        <p class="small text-muted">Per Annum for Placement and Per Month for Internship.</p>
                 </div>
                 <div class="form-group ">
                  <label class="control-label col-sm-2" for="Grade">
                   Grade
                  </label>
                  <div class="col-sm-10">
                   {{form.grade}}
                  </div>
                 </div>
                 <div class="form-group ">
                  <label class="control-label col-sm-2" for="Cut-Off">
                   Cut-Off
                  </label>
                  <div class="col-sm-10">
                   {{form.cutoff}}
                  </div>
                 </div>
                 <div class="form-group ">
                  <label class="control-label col-sm-2" >
                   Branch Allowed
                  </label>
                  <div class="col-sm-10">
                      <div class="row">
                      {%for box in form.branch_allowed %}
                      <div class="form-check form-check-inline">                          
                              <div class="col-lg-2 col-md-3 col-sm-4">
                          {{box.tag}}
                          <label class="form-check-label" for="{{box.id_for_label}}">{{box.choice_label}}</label>
                                  </div>                       
                      </div>
                      {%endfor%}
                           </div>
                  </div>
                 </div>
                 <div class="form-group ">
                  <label class="control-label col-sm-2" for="BacklogsAllowed">
                   Backlogs Allowed
                  </label>
                  <div class="col-sm-10">
                   {{form.backlogs_allowed}}

                      
                  </div>
                 </div>
              <!--   <div class="form-group ">
                  <label class="control-label col-sm-2" for="CompanyDetails">
                   Company Details
                  </label>
                  <div class="col-sm-10">
                   <textarea class="form-control" cols="40" id="CompanyDetails" name="CompanyDetails" placeholder="Company Details" rows="10"></textarea>
                  </div>
                 </div>-->
                 <div class="form-group ">
                  <label class="control-label col-sm-2" for="ClosingDate">
                   Closing Date
                  </label>
                  <div class="col-sm-10 input-group datepicker" data-provide="datepicker">
                   {{form.closing_date}}
                  </div>
                 </div>
                      <div class="form-group ">
                  <label class="control-label col-sm-2" for="cap">
                   Cap
                  </label>
                  <div class="col-sm-10">
                   {{form.cap}}
                  </div>
                 </div>
                    <div class="form-group">
                    <div class="col-sm-10">
                        <p>Enter -1 if there is no cap.</p>
                    </div>
                </div>
                         <div class="form-group ">
                  <label class="control-label col-sm-2" for="open_reg">
                   Registration Status
                  </label>
                  <div class="col-sm-10">
                   {{form.open_reg}}
                  </div>
                 </div>
                    {%csrf_token%}
                 <div class="form-group">
                  <div class="col-sm-10 col-sm-offset-2">
                   <button class="btn btn-default " name="submit" type="submit">
                    Submit
                   </button>
                  </div>
                 </div>
                </form>
               </div>
              </div>
             </div>
        </div>
{%endblock%}

management/templates/add_db.html
{%extends 'skeleton.html'%}

{%block head%}
{%include 'head.html'%}
{%include 'search_company_head.html'%} 
<style>
    td { 
    padding: 10px !important;
}
</style>
{%endblock%}


{%block body%}

<div class="bootstrap-iso">
         <div class="container-fluid">
          <div class="row">
           <div class="col-md-6 col-sm-6 col-xs-12">
               {%if form.errors%}
{%for field in form%}
<ul>
    {%for error in field.errors%}
    <li>{{field.name}} : {{error}}</li>
    {%endfor%}
</ul>
{%endfor%}
{%endif%}
          <form method="post" enctype="multipart/form-data" name="myfile">
    {% csrf_token %}
    {{form.myfile}}
    <button type="submit">Upload</button>
  </form>
               
                   {%if messages%}
               
{%for message in messages%}
<h4 class="title">{{message}}</h4>
{%endfor%}

{%endif%}
               <h5><b>Recommended Excel Format</b></h5>
               <table border="1">
                   <tr>
                       <td>Roll Number</td>
                       <td>Email</td>
                       <td>Sem 1</td>
                       <td>Sem 2</td>
                       <td>Sem 3</td>
                       <td>Sem 4</td>
                       <td>Sem 5</td>
                       <td>Sem 6</td>
                       <td>CGPA</td>
                       <td>Batch</td>
                   </tr>
                   <tr>
                       <td>2016UAB1234</td>
                       <td>example@example.com</td>
                       <td>9.9</td>
                       <td>9.9</td>
                       <td>9.9</td>
                       <td>9.9</td>
                       <td>9.9</td>
                       <td>9.9</td>
                       <td>9.9</td>
                       <td>2020</td>

                   </tr>
               </table>
               <h4><b>1<sup>st</sup> row should be header</b></h4>
           </div>
         </div>
        </div>
    </div>


{%endblock%}

management/templates/head.html
{% load static%}    
    <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>TNP Portal</title>
<meta name="description" content="TNP NSIT Portal for students. See Company. Register For Company.">
    <meta name="keywords" content="TNP NSIT tnp nsit portal placement yash Yash kulshreshtha">
<meta property="og:url" content="http://www.yash99.me/" />
<meta property="og:site_name" content="TNP NSIT Portal" />
<meta property="article:author" content="https://www.facebook.com/yksmbkkr" />
<meta property="article:tag" content="TNP" />
<meta property="article:tag" content="NSIT" />
<meta property="article:tag" content="Portal" />
<meta property="article:tag" content="youth" />
<meta property="article:tag" content="Delhi" />
<!--This is creation of Ankit Aggarwal and Yash Kulshreshtha
    Complete Backend and Student Area Frontend developed by Yash Kulshreshtha https://facebook.com/yksmbkkr
    Management Area Frontend developed by Ankit Aggarwal https://facebook.com/Ankit6899
    -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384- BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
        <link rel="stylesheet" href="{%static 'Css/HomePage.css'%}">
<link rel="stylesheet" href="{%static 'Css/PageHeader.css'%}">

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jszip-2.5.0/dt-1.10.18/b-1.5.4/b-html5-1.5.4/datatables.min.css"/>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
  <script>
  $(function() {
    $( "#id_closing_date" ).datepicker();
  });
  </script>

management/templates/login_head.html
{% load static%}    
        <link rel="stylesheet" href="{%static 'Css/login.css'%}"> 

management/templates/search_user_extended.html
{%extends 'skeleton.html'%}

{%block head%}
{%include 'head.html'%}
{%include 'search_company_head.html'%} 
<style>
.hard_left {
  position:absolute;
  *position: relative; /*ie7*/
  left:10px; 
  width:150px;
  background-color:#f9fafc !important;
}
.next_left {
  position:absolute;
  *position: relative; /*ie7*/
  left:150px; 
  width:150px;
  background-color:#f9fafc !important;
}
.inner {
  overflow-x:scroll;
  overflow-y:visible;
  width:auto; 
  margin-left:285px;
}
</style>
{%endblock%}


{%block body%}

<div class="bootstrap-iso">
         <div class="container-fluid">
          <div class="row">
           <div class="col-md-6 col-sm-6 col-xs-12">
               {%if form.errors%}
{%for field in form%}
<ul>
    {%for error in field.errors%}
    <li>{{field.name}} : {{error}}</li>
    {%endfor%}
</ul>
{%endfor%}
{%endif%}
            <form class="form-horizontal" method="post">
             <div class="form-group ">
              <label class="control-label col-sm-2" for="i_slug">
               Search For
              </label>
              <div class="col-sm-10">
               {{form.slug}}
              </div>
             </div>
                <div class="form-group">
                    <div class="col-sm-10">
                        <p>Leave this field empty to get whole list with or without filters.</p>
                    </div>
                </div>
             <div class="form-group ">
              <label class="control-label col-sm-2" for="id_field_type">
               Placement Filter
              </label>
              <div class="col-sm-10">
               {{form.place}}
              </div>
             </div>
                <div class="form-group ">
              <label class="control-label col-sm-2" for="id_field_type">
               Branch Filter
              </label>
              <div class="col-sm-10">
               {{form.branch}}
              </div>
             </div>
                 <div class="form-group ">
              <label class="control-label col-sm-2" for="id_field_type">
               Batch Filter
              </label>
              <div class="col-sm-10">
               {{form.batch}}
              </div>
             </div>
                <div class="form-group">
                    <div class="col-sm-10">
                        <p>Leave filter field empty for the filters which you don't wish to apply</p>
                    </div>
                </div>
                 <input id="prodId" name="prodId" type="hidden" value="xm234jq">
                {%csrf_token%}
             <div class="form-group">
              <div class="col-sm-10 col-sm-offset-2">
               <button class="btn btn-default btn-block" name="submit" type="submit">
                Submit
               </button>
              </div>
             </div>
            </form>
               
                   {%if messages%}
               
{%for message in messages%}
<h3 class="title">{{message}}</h3>
{%endfor%}

{%endif%}
               
           </div>
          
             {%if clist%}
            
                <div class="col-md-10 ml-2">
                    

<div>
            <h3 class="title">{{smsg}}</h3>
            <div class="inner"><table id="query-table" class="table table-bordered" style="display: block !important; overflow-x: auto !important; white-space: nowrap !important; ">
                <thead>
                    <tr>
                        <th scope="col" class="hard_left">Name</th>
                        <th scope="col" class="next_left">Roll No</th>
                        <th scope="col">Batch</th>
                        <th scope="col">Branch</th>
                        <th scope="col">Email</th>
                        <th scope="col">Mobile</th>
                        <th scope="col">Alternate Mobile</th>
                        <th scope="col">CGPA</th>
                        <th scope="col">CGPA with drop</th>
                        <th scope="col">Sem 1</th>
                        <th scope="col">Sem 2</th>
                        <th scope="col">Sem 3</th>
                        <th scope="col">Sem 4</th>
                        <th scope="col">Sem 5</th>
                        <th scope="col">Sem 6</th>
                        <th scope="col">Backlogs</th>
                        <th scope="col">12th marks</th>
                         <th scope="col">12th passing year</th>
                         <th scope="col">10th marks</th>
                        <th scope="col">10th passing year</th>
                        <th scope="col">Company of Internship</th>
                        <th scope="col">Gender</th>
                        <th scope="col">Category</th>
                        <th scope="col">Father's Name</th>
                         <th scope="col">Father's Occupation</th>
                         <th scope="col">Mother's Name</th>
                        <th scope="col">Mother's Occupation</th>
                        <th scope="col">Present Address</th>
                        <th scope="col">Permanent Address</th>
                        <th scope="col">Dream</th>
                        <th scope="col">A++</th>
                        <th scope="col">A+</th>
                        <th scope="col">A</th>
                    </tr>
                </thead>
                <tbody>
                    {%for c in clist%}
                    <tr>
                        <th scope="row" class="hard_left"><a href="{%url 'management:modify_user' c.p.user.id%}">{{c.p.f_name}}&nbsp;{{c.l_name}}</a></th>
                        <td class="next_left">{{c.p.roll_no}}</td>
                        <td >{{c.p.batch.name}}</td>
                        <td >{{c.p.branch}}</td>
                        <td>{{c.p.user.email}}</td>
                        <td>{{c.p.mobile}}</td>
                        <td>{{c.p.alternate_mobile}}</td>
                        <td>{{c.p.be_marks}}</td>
                        <td>{{c.p.cgpa_drop}}</td>
                        <td>{{c.p.sem1}}</td>
                        <td>{{c.p.sem2}}</td>
                        <td>{{c.p.sem3}}</td>
                        <td>{{c.p.sem4}}</td>
                        <td>{{c.p.sem5}}</td>
                        <td>{{c.p.sem6}}</td>
                        <td>{{c.p.backlogs}}</td>
                        <td>{{c.p.marks_12}}</td>
                        <td>{{c.p.passing_year_12}}</td>
                        <td>{{c.p.marks_11}}</td>
                        <td>{{c.p.passing_year_10}}</td>
                        <td>{{c.p.intern_company}}</td>
                        <td>{{c.p.gender}}</td>
                        <td>{{c.p.category}}</td>
                        <td>{{c.p.father}}</td>
                        <td>{{c.p.father_occupation}}</td>
                        <td>{{c.p.mother}}</td>
                        <td>{{c.p.mother_occupation}}</td>
                        <td>{{c.p.address}}</td>
                        <td>{{c.p.permanent_address}}</td>
                        <td>{{c.dream}}</td>
                        <td>{{c.app}}</td>
                        <td>{{c.ap}}</td>
                        <td>{{c.a}}</td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table></div>

</div>
                     <div class="col-md-10 col-md-offset-1">
                  
        <button id="customXLSButton" class="btn btn-lg btn-block btn-green">Download</button>

              </div>
                  


                </div>
             
            </div>
             {%endif%}
         </div>
        </div>


{%endblock%}

{%block extrascripts%}
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.13.1/xlsx.core.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/blob-polyfill/2.0.20171115/Blob.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/TableExport/5.0.2/js/tableexport.min.js"></script>
<script>
    var tableId = 'query-table';
    var ExportButtons = document.getElementById(tableId);
    var instance = new TableExport(ExportButtons, {
        formats: ['xlsx'],
        exportButtons: false
    });
    // **** jQuery **************************
    //    $(ExportButtons).tableExport({
    //        formats: ['xls'],
    //        exportButtons: false
    //    });
    // **************************************
    var XLSX = instance.CONSTANTS.FORMAT.XLSX;
    //                                          // "id"  // format
    var exportDataXLSX = instance.getExportData()[tableId][XLSX];
    // get filesize
    var bytesXLSX = instance.getFileSize(exportDataXLSX.data, exportDataXLSX.fileExtension);
    console.log('filesize (XLSX):', bytesXLSX + 'B');
    var XLSbutton = document.getElementById('customXLSButton');
    XLSbutton.addEventListener('click', function (e) {
        //                   // data             // mime                 // name                 // extension
        instance.export2file(exportDataXLSX.data, exportDataXLSX.mimeType, exportDataXLSX.filename, exportDataXLSX.fileExtension);
    });
</script>



{%endblock%}

management/templates/usrs_dropdown_list_options.html
{% for usr in usrs %}
<option value="{{ usr.pk }}">{{ usr.user.username }} ( {{ usr.user.student_profile.f_name }} {{ usr.user.student_profile.l_name }} )</option>
{% endfor %}