management/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    #url(r'^check/$', views.check),
    #url(r'^xlsx/$', views.xlxs_try),
    #url(r'^user_xlsx/$', views.user_xlsx,name='user_xlsx'),
    url(r'^add-student-db/$', views.student_db_add,name='student_db'),
    url(r'^update-student-db/$', views.student_db_update,name='student_db_update'),
    url(r'^$', views.home, name= 'm_home' ),
    #url(r'^trial/$', views.trial,),
    url(r'^add_user/$', views.add_user, name= 'add_user' ),
    url(r'^download_resume/$', views.get_resume_zip, name= 'r_downloader' ),
    url(r'^add_manager/$', views.create_manager, name= 'add_manager' ),
    url(r'^add_company/$', views.add_company, name= 'add_company' ),
    url(r'^login/$', auth_views.login, {'template_name': 'new/login.html', 'extra_context':{'log_nav_active':'active'}}, name='login'),
    url(r'^logout/$',auth_views.logout, {'next_page': 'management:login'}, name = 'logout'),
    url(r'^mod_pass/$', views.changepass, name= 'mod_pass' ),
    url(r'^search_company/$', views.search_company, name= 'search_company' ), 
    url(r'^search_user/$', views.search_user_extended, name= 'search_user' ), 
    url(r'^view-reg/$', views.view_registrations, name= 'view_reg' ),
    url(r'^view-reg-2/$', views.view_registrations_new, name= 'view_reg_new' ),
    url(r'^edit_company/(?P<id>[\d]+)/$', views.edit_company, name= 'edit_company' ),
    url(r'^search_company/(?P<field_type>[a-z]{4})/(?P<slug>[-\w+]+)/$', views.search_company, name= 'search_company_result' ),    
    url(r'^search_user/(?P<field_type>[_\w+]+)/(?P<slug>[-\w\s+]+)/$', views.search_user, name= 'search_user_result' ),    
    url(r'^view-reg/(?P<slug>[-\w\s+]+)/(?P<f_choice>[-\w\s+]+)/$', views.view_registrations, name= 'view_reg_search' ),    
    url(r'^view-reg-2/(?P<slug>[-\w\s+]+)/(?P<f_choice>[-\w\s+]+)/$', views.view_registrations_new, name= 'view_reg_search_new' ),
    url(r'^add-placement/$', views.add_placement_ajax, name= 'add_placement' ),
    url(r'^add-ppo/$', views.add_ppo_view, name= 'add_ppo' ),
    url(r'^get-ajax/$', views.load_user, name= 'ajax_user' ),
    url(r'^ban/$', views.ban_select, name= 'ban_select' ),
    url(r'^batch-email/$', views.batch_email_view, name= 'batch_emails' ),
    url(r'^send-sms/$', views.send_sms_view, name= 'send_sms' ),
    url(r'^batch-email-get-email-ajax/$', views.get_email_address_list, name= 'batch_email_get_email_ajax' ),
    url(r'^batch-email-boto-call-ajax/$', views.send_mail_boto_call_ajax, name= 'email_boto_call_ajax' ),
    url(r'^get-rej-ajax/$', views.get_registration_ajax, name= 'get_reg_ajax' ),
    url(r'^batch-email-template-preview-ajax/$', views.batch_email_template_preview_ajax, name= 'get_email_preview_ajax' ),
    url(r'^batch-email-select-ajax/$', views.batch_email_select_ajax, name= 'get_select_ajax' ),
    url(r'^ban/(?P<roll_no>[0-9]{1,4}[a-zA-Z]{1,5}[0-9]{1,4})/$', views.ban_proceed, name= 'ban_proceed' ),
    url(r'^revoke-ban/(?P<roll_no>[0-9]{1,4}[a-zA-Z]{1,5}[0-9]{1,4})/$', views.revoke_ban, name= 'revoke_ban' ),
    url(r'^modify-user/(?P<uid>[0-9]{1,20})/$', views.modify_user, name= 'modify_user' ),
    #url(r'^company_search/(?P<field_type>[a-z]{4})/(?P<slug>[-\w]+)')
    #This py file developed by Yash Kulshreshtha
#visit https://fb.com/yksmbkkr
    ]

tnp/urls.py
"""
Definition of urls for tnp.
"""

from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from management import views as m_views
from student import views as s_views
from django.conf.urls import handler404, handler500
from . import views


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', tnp.views.home, name='home'),
    # url(r'^tnp/', include('tnp.tnp.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^ps-r558u/', include(admin.site.urls)),
    url(r'^management/',include('management.urls', namespace='management')),
    url(r'^',include('student.urls', namespace='student')),
    #url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'password_reset_form.html', 'email_template_name':'password_reset_email.html','subject_template_name':'password_reset_subject.txt','extra_context':{'pswd_nav_active':'active color-change'}}, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name':'password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name':'password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, {'template_name':'password_reset_complete.html'}, name='password_reset_complete'),
   #url(r'^su/$', m_views.search_user_extended),
    #url(r'^mdc/$', s_views.mdc),
]

handler404 = views.error_404
handler500 = views.error_500
admin.site.site_header = "TNP Admin Portal"
admin.site.site_title = "TNP Admin Portal"
admin.site.index_title = "Welcome to TNP Admin Portal"

management/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.conf import settings
from .models import *
from student.models import s_registration,student_profile
from .choices import *
from django.template.defaultfilters import filesizeformat
from django.utils.translation import ugettext_lazy as _
from django.core.validators import RegexValidator
from student.models import student_profile as s_profile
import re
import json
from django.utils import timezone as django_time

custom_validator = RegexValidator(r'^[-\w\s+]*$', 'Only alphanumeric characters including space and hyphen are allowed')
reg_id_validator= RegexValidator(r'^[\d]*$', 'Only alphanumeric characters including space and hyphen are allowed')
cap_validator=RegexValidator(r'^(\-?[1]{1})$|^([0-9]{1,50})$','Only integers are allowed')

class file_try_form(forms.Form):
    myfile = forms.FileField()

    def clean_myfile(self):
            myfile = self.cleaned_data['myfile']
            content_type = myfile.content_type.split('/')[1]
            if (myfile.name.split('.')[-1]).upper() != 'XLSX':
                self.add_error('myfile','Only XLSX files are supported.')
            if content_type in settings.CONTENT_TYPES:
                if myfile._size > settings.MAX_UPLOAD_SIZE:
                    raise forms.ValidationError(_('Please keep filesize under %(permitsize)s. Current filesize %(thissize)s'), code='InvalidFileSize', params ={'permitsize' : filesizeformat(settings.MAX_UPLOAD_SIZE), 'thissize':filesizeformat(myfile._size)},)
            else:
                raise forms.ValidationError(_('File type is not supported. Only XLSX formated excel sheets are supported.'), code = 'InvalidFileType',)
            return myfile

class PasswordChangeCustomForm(PasswordChangeForm):
    def __init__(self, user, *args, **kwargs):
        super(PasswordChangeCustomForm, self).__init__(user, *args, **kwargs)
        self.fields['old_password'].widget.attrs.update({'class': 'form-control', 'placeholder':'Old Password'})
        self.fields['new_password1'].widget.attrs.update({'class': 'form-control', 'placeholder':'New Password'})
        self.fields['new_password2'].widget.attrs.update({'class': 'form-control', 'placeholder':'Confirm Password'})

#This py file developed by Yash Kulshreshtha
#visit https://fb.com/yksmbkkr

class create_user_form(forms.Form):
    username = forms.CharField(max_length=11, required = True, widget = forms.TextInput(attrs = {'class':'form-control', 'placeholder':'RollNumber', 'aria-describedby':'basic-addon1'}))
    email = forms.EmailField(max_length=254, required = True, widget = forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Email', 'aria-describedby':'basic-addon1'}))

class create_manager_form(forms.Form):
    username = forms.CharField(max_length=11, required = True, widget = forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Username', 'aria-describedby':'basic-addon1'}))
    email = forms.EmailField(max_length=254, required = True, widget = forms.EmailInput(attrs = {'class':'form-control', 'placeholder':'Email', 'aria-describedby':'basic-addon1'}))

class add_company_form(forms.ModelForm):
    name = forms.CharField(max_length=100, required = True, widget = forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Name of Company', 'aria-describedby':'basic-addon1'}))
    for_batch = forms.ModelChoiceField(queryset=current_batch_year.objects.all(),empty_label='Select Batch', required = True, widget=forms.Select(attrs={'class':'form-control select2-single'}))
    ctc = forms.CharField(max_length=70, required = True, widget = forms.TextInput(attrs = {'class':'form-control', 'placeholder':'CTC (Per Annum for Placement and Per Month for Internship.)', 'aria-describedby':'basic-addon1', 'pattern':'[0-9]{1,50}','title':'Integer Only'}))
    grade = forms.ModelChoiceField(queryset=company_grade.objects.all(),empty_label='Select Grade', required = True, widget=forms.Select(attrs={'class':'form-control select2-single'}))
    cutoff= forms.DecimalField(max_digits=5,decimal_places=2,required = True,widget = forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Cut-Off', 'aria-describedby':'basic-addon1'}))
    branch_allowed = forms.ModelMultipleChoiceField(queryset=branches.objects.all(),required = True,
                                                   widget=forms.SelectMultiple(attrs={'class': 'js-example-basic-multiple form-control',
                                                    'data-placeholder': 'Select Fields'}))
    backlogs_allowed = forms.IntegerField(required = True,widget = forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Backlogs Allowed', 'aria-describedby':'basic-addon1'}))
    closing_date = forms.DateField(required = True, widget = forms.TextInput(attrs = {'class':'form-control datepicker', 'placeholder':'Closing Date', 'data-provide':'datepicker'}))
    cap = forms.CharField(validators=[cap_validator], max_length=70, required = False, initial='-1',widget = forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Cap', 'aria-describedby':'basic-addon1', 'pattern':'\-?[0-9]{1,50}','title':'Integer Only'}))
    open_reg = forms.ChoiceField(choices= open_reg_choice, required = True, widget=forms.Select(attrs={'class': 'select form-control'}))

    class Meta:
        model = company
        fields = (
            'name',
            'for_batch',
            'ctc',
            'grade',
            'cutoff',
            'branch_allowed',
            'backlogs_allowed',
            'closing_date',
            'cap',
            'open_reg',
            )

class search_company_form(forms.Form):
    slug = forms.CharField(required = True, max_length=20, widget = forms.TextInput(attrs={'class':'form-control'}))
    field_choice = forms.ChoiceField(choices= c_search_choice, required = True, widget=forms.Select(attrs={'class': 'select form-control'}))

class search_student_form(forms.Form):
    slug = forms.CharField(validators=[custom_validator], required = True, max_length=20, widget = forms.TextInput(attrs={'class':'form-control'}))
    field_choice = forms.ChoiceField(choices= s_search_choice, required = True, widget=forms.Select(attrs={'class': 'select form-control'}))

class search_reg_form(forms.Form):
    slug = forms.CharField(validators=[custom_validator], required = True, max_length=20, widget = forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter Name of Company'}))
    field_choice = forms.ChoiceField(choices= reg_search_choice, required = True, widget=forms.Select(attrs={'class': 'select form-control'}))
    batch_choice = forms.ModelChoiceField(required=False, queryset=current_batch_year.objects.all(), empty_label = 'None Selected', widget=forms.Select(attrs={'class':'select form-control'}))


class add_placement_form(forms.Form):
    rid = forms.CharField(validators=[reg_id_validator], required = True, max_length=6, widget = forms.TextInput(attrs={'class':'form-control'}))


class trial_form(forms.Form):
    cmpn = forms.ModelChoiceField(required=True,queryset=company.objects.all(),widget=forms.Select(attrs={'class':'form-control js-example-basic-single','data-live-search':'true'}))
    roll_no = forms.ModelMultipleChoiceField(required=True,queryset=User.objects.none(), widget=forms.SelectMultiple(attrs={'class': 'js-example-basic-multiple form-control',
                                                    'data-placeholder': 'Select Roll No'}))
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['roll_no'].queryset =User.objects.none()

        if 'cmpn' in self.data:
            try:
                cmpn_id = int(self.data.get('cmpn'))
                self.fields['roll_no'].queryset = s_registration.objects.filter(company__id=cmpn_id).order_by('reg_id')
            except (ValueError, TypeError):
                pass

class search_user_extended_form(forms.Form):
    slug = forms.CharField(required=False, validators=[custom_validator], widget = forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter Roll Number or Name'}))
    place = forms.ChoiceField(required=False, choices=place_choice,widget=forms.Select(attrs={'class':'form-control js-example-basic-single','data-live-search':'true'}))
    branch = forms.ModelMultipleChoiceField(required=False, queryset=branches.objects.all(), widget=forms.SelectMultiple(attrs={'class':'form-control js-example-basic-multiple','data-live-search':'true'}))
    batch = forms.ModelChoiceField(required=False, queryset=current_batch_year.objects.all(), empty_label = 'None Selected', widget=forms.Select(attrs={'class':'form-control js-example-basic-single','data-live-search':'true'}))

class resume_download_form(forms.Form):
    cmpn = forms.ModelChoiceField(required=True,queryset=company.objects.all(), empty_label='Select Company', widget=forms.Select(attrs={'class':'form-control js-example-basic-single','data-live-search':'true'}))

class ban_select_form(forms.Form):
    rollno = forms.CharField(required = True, max_length=11, widget = forms.TextInput(attrs={'class':'form-control','pattern':'[0-9]{1,4}[a-zA-Z]{1,5}[0-9]{1,4}','title':'NSIT Roll Number Format - 0123ABC4567'}))
    #type_choice = forms.ChoiceField(choices= ban_select_choice, required = True, widget=forms.Select(attrs={'class': 'select form-control'}))

class ban_form(forms.Form):
    field1 = forms.DateField(required = False, label = 'Ban Till date :',widget = forms.TextInput(attrs = {'class':'form-control datepicker', 'placeholder':'Ban till date :', 'data-provide':'datepicker'}))
    field2 = forms.ModelMultipleChoiceField(required=False, queryset=company.objects.all(), label='Ban in companies : ',widget=forms.SelectMultiple(attrs={'class':'form-control js-example-basic-multiple','data-live-search':'true'}))

management/templates/new/add_placement.html
{% extends 'new/skeleton.html' %}

{%block body%}
<div class="container-fluid">
    <div class="row">
        {%for message in messages%}
        <div class="col-md-10 col-sm-12 mr-auto ml-auto">
        
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
  {{message}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
       
            </div>
        {%endfor%}

        {%if form.errors%}
        <div class="col-md-10 col-sm-12 mr-auto ml-auto mt-4">        
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                 {{form.errors}}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>       
            </div>
        {%endif%}

        <div class="col-md-10 col-sm-12 mr-auto ml-auto mt-4">
            <h4>Add Placements : </h4>
            <form method="post" id="place_form" data-rollno-url="{%url 'management:ajax_user'%}">
               <div class="form-group ">
                  <label class="control-label col-sm-2" for="Grade">
                   Select Company
                  </label>
                  <div class="col-sm-10">
                   {{form.cmpn}}
                  </div>
                 </div>
    
    <div class="form-group ">
                  <label class="control-label col-sm-2" for="Grade">
                   Select Students
                  </label>
                  <div class="col-sm-10">
                   {{form.roll_no}}
                  </div>
                 </div>
                {%csrf_token%}
                <button class="btn btn-primary btn-block" type="submit">Save</button>
            </form>
        </div>
    </div>
</div>
{%endblock%}

{%block script %}
  <script>
    $("#id_cmpn").change(function () {
      var url = $("#place_form").attr("data-rollno-url");  // get the url of the `load_cities` view
      var company = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
          data: {
              'company': company      // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_roll_no").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });
      });
      
  </script>
{%endblock %}

management/templates/new/skeleton.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>TNP Portal | Admin</title>

  <!-- Custom fonts for this template-->
  <link href="{%static 'new/vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'new/css/sb-admin-2.min.css' %}" rel="stylesheet">
  <link href="{% static 'new/css/custom.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.9/css/bootstrap-select.css">
 <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.css" />
    <link href="{% static 'new/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/fixedcolumns/3.2.6/css/fixedColumns.dataTables.min.css" />

{% block head %}
{% endblock %}

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'management:m_home'%}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-user-secret"></i>
        </div>
        <div class="sidebar-brand-text mx-3">TNP Admin</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
        {% include 'new/nav-side.html' %}

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <!--<form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>-->

          <!-- Topbar Navbar -->
          {% include 'new/nav-top.html' %}

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
          {% block body%}
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

        </div>
        <!-- /.container-fluid -->
          {% endblock%}

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy;  2019, Developed by <a href="https://fb.com/Ankit6899">Ankit Agarwal</a> &amp; <a href="https://fb.com/yksmbkkr">Yash Kulshreshtha</a></span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{%url 'management:logout'%}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'new/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'new/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'new/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'new/js/sb-admin-2.min.js' %}"></script>
    <script src="{% static 'new/vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'new/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
        <script src="https://cdn.datatables.net/fixedcolumns/3.2.6/js/dataTables.fixedColumns.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.9/js/bootstrap-select.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.js"></script>
<script>
    $(document).ready(function() {
        $(".select2-single, .select2-multiple, .js-example-basic-single").select2();
        $('.js-example-basic-multiple').select2({
    closeOnSelect: false
        });
        $('.selectpicker').selectpicker();        
        $('.datepicker').datepicker();
        {% if not hidden_form %}
        $('#dataTable').DataTable({
            fixedColumns: true,
        });
        {% endif %}
     });
</script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.13.1/xlsx.core.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/blob-polyfill/2.0.20171115/Blob.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/TableExport/5.0.2/js/tableexport.min.js"></script>
<script>
    var tableId = 'dataTable';
    var ExportButtons = document.getElementById(tableId);
    var instance = new TableExport(ExportButtons, {
        formats: ['xlsx'],
        exportButtons: false
    });
    // **** jQuery **************************
    //    $(ExportButtons).tableExport({
    //        formats: ['xls'],
    //        exportButtons: false
    //    });
    // **************************************
    var XLSX = instance.CONSTANTS.FORMAT.XLSX;
    //                                          // "id"  // format
    var exportDataXLSX = instance.getExportData()[tableId]['xlsx'];
    // get filesize
    var bytesXLSX = instance.getFileSize(exportDataXLSX.data, exportDataXLSX.fileExtension);
    console.log('filesize (XLSX):', bytesXLSX + 'B');
    var XLSbutton = document.getElementById('customXLSButton');
    XLSbutton.addEventListener('click', function (e) {
        //                   // data             // mime                 // name                 // extension
        instance.export2file(exportDataXLSX.data, exportDataXLSX.mimeType, exportDataXLSX.filename, exportDataXLSX.fileExtension);
    });
</script>
{% block script %}
{% endblock %}

</body>

</html>