management/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    #url(r'^check/$', views.check),
    #url(r'^xlsx/$', views.xlxs_try),
    #url(r'^user_xlsx/$', views.user_xlsx,name='user_xlsx'),
    url(r'^add-student-db/$', views.student_db_add,name='student_db'),
    url(r'^update-student-db/$', views.student_db_update,name='student_db_update'),
    url(r'^$', views.home, name= 'm_home' ),
    #url(r'^trial/$', views.trial,),
    url(r'^add_user/$', views.add_user, name= 'add_user' ),
    url(r'^download_resume/$', views.get_resume_zip, name= 'r_downloader' ),
    url(r'^add_manager/$', views.create_manager, name= 'add_manager' ),
    url(r'^add_company/$', views.add_company, name= 'add_company' ),
    url(r'^login/$', auth_views.login, {'template_name': 'new/login.html', 'extra_context':{'log_nav_active':'active'}}, name='login'),
    url(r'^logout/$',auth_views.logout, {'next_page': 'management:login'}, name = 'logout'),
    url(r'^mod_pass/$', views.changepass, name= 'mod_pass' ),
    url(r'^search_company/$', views.search_company, name= 'search_company' ), 
    url(r'^search_user/$', views.search_user_extended, name= 'search_user' ), 
    url(r'^view-reg/$', views.view_registrations, name= 'view_reg' ),
    url(r'^view-reg-2/$', views.view_registrations_new, name= 'view_reg_new' ),
    url(r'^edit_company/(?P<id>[\d]+)/$', views.edit_company, name= 'edit_company' ),
    url(r'^search_company/(?P<field_type>[a-z]{4})/(?P<slug>[-\w+]+)/$', views.search_company, name= 'search_company_result' ),    
    url(r'^search_user/(?P<field_type>[_\w+]+)/(?P<slug>[-\w\s+]+)/$', views.search_user, name= 'search_user_result' ),    
    url(r'^view-reg/(?P<slug>[-\w\s+]+)/(?P<f_choice>[-\w\s+]+)/$', views.view_registrations, name= 'view_reg_search' ),    
    url(r'^view-reg-2/(?P<slug>[-\w\s+]+)/(?P<f_choice>[-\w\s+]+)/$', views.view_registrations_new, name= 'view_reg_search_new' ),
    url(r'^add-placement/$', views.add_placement_ajax, name= 'add_placement' ),
    url(r'^add-ppo/$', views.add_ppo_view, name= 'add_ppo' ),
    url(r'^get-ajax/$', views.load_user, name= 'ajax_user' ),
    url(r'^ban/$', views.ban_select, name= 'ban_select' ),
    url(r'^batch-email/$', views.batch_email_view, name= 'batch_emails' ),
    url(r'^send-sms/$', views.send_sms_view, name= 'send_sms' ),
    url(r'^batch-email-get-email-ajax/$', views.get_email_address_list, name= 'batch_email_get_email_ajax' ),
    url(r'^batch-email-boto-call-ajax/$', views.send_mail_boto_call_ajax, name= 'email_boto_call_ajax' ),
    url(r'^get-rej-ajax/$', views.get_registration_ajax, name= 'get_reg_ajax' ),
    url(r'^batch-email-template-preview-ajax/$', views.batch_email_template_preview_ajax, name= 'get_email_preview_ajax' ),
    url(r'^batch-email-select-ajax/$', views.batch_email_select_ajax, name= 'get_select_ajax' ),
    url(r'^ban/(?P<roll_no>[0-9]{1,4}[a-zA-Z]{1,5}[0-9]{1,4})/$', views.ban_proceed, name= 'ban_proceed' ),
    url(r'^revoke-ban/(?P<roll_no>[0-9]{1,4}[a-zA-Z]{1,5}[0-9]{1,4})/$', views.revoke_ban, name= 'revoke_ban' ),
    url(r'^modify-user/(?P<uid>[0-9]{1,20})/$', views.modify_user, name= 'modify_user' ),
    #url(r'^company_search/(?P<field_type>[a-z]{4})/(?P<slug>[-\w]+)')
    #This py file developed by Yash Kulshreshtha
#visit https://fb.com/yksmbkkr
    ]

student/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^activation/$',views.student_activation, name='s_activation'),
    url(r'^forgot-password/$',views.forgot_password, name='s_forgot_pass'),
    url(r'^change-password/$',views.s_changepass, name='s_change_pass'),
    url(r'^create-profile/$',views.create_profile, name='s_create_profile'),
    url(r'^profile/$',views.student_profile_visit, name='s_profile'),
    url(r'^registration/(?P<cid>[\d]+)/$',views.registration_redirects, name='company_reg'),
    url(r'^placement-registration/(?P<cid>[\d]+)/$',views.placement_registeration, name='p_reg'),
    url(r'^placement-registration/(?P<cid>[\d]+)/(?P<rid>[\d]+)/$',views.placement_registeration, name='s_p_reg'),
    url(r'^internship-registration/(?P<cid>[\d]+)/$',views.internship_registeration, name='i_reg'),
    url(r'^internship-registration/(?P<cid>[\d]+)/(?P<rid>[\d]+)/$',views.internship_registeration, name='s_i_reg'),
    url(r'^login/$', auth_views.login, {'template_name': 's_login.html'}, name='s_login'),
    url(r'^logout/$',auth_views.logout, {'next_page': 'student:s_login'}, name = 's_logout'),
    url(r'^companies/$',views.s_home, name='s_home'),
    url(r'^$',views.all_home, name='all_home'),
    url(r'^alumni/$',views.alumni_s, name='alumni_s'),
    url(r'^courses/$',views.courses_s, name='courses_s'),
    url(r'^faculty/$',views.faculty_s, name='faculty_s'),
    url(r'^history/$',views.history_s, name='history_s'),
    url(r'^policy/$',views.policy_s, name='policy_s'),
    url(r'^procedure/$',views.procedure_s, name='procedure_s'),
    url(r'^students/$',views.students_life_s, name='students_s'),
    url(r'^resume-drive/$',views.resume_management_student, name='s_resume'),
    url(r'^contact-us/$',views.contact_us, name='contact_us'),
    url(r'^search/(?P<slug>[-\w\s+]+)/$',views.s_home, name='s_home_search'),
    url(r'^my-registrations/$',views.my_reg_list, name='my_reg'),
    url(r'^cancel-registrations/(?P<reg_id>[\d]+)/$',views.delete_registration, name='del_reg'),
    ]

#This py file developed by Yash Kulshreshtha
#visit https://fb.com/yksmbkkr

tnp/urls.py
"""
Definition of urls for tnp.
"""

from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from management import views as m_views
from student import views as s_views
from django.conf.urls import handler404, handler500
from . import views


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', tnp.views.home, name='home'),
    # url(r'^tnp/', include('tnp.tnp.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^ps-r558u/', include(admin.site.urls)),
    url(r'^management/',include('management.urls', namespace='management')),
    url(r'^',include('student.urls', namespace='student')),
    #url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'password_reset_form.html', 'email_template_name':'password_reset_email.html','subject_template_name':'password_reset_subject.txt','extra_context':{'pswd_nav_active':'active color-change'}}, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name':'password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name':'password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, {'template_name':'password_reset_complete.html'}, name='password_reset_complete'),
   #url(r'^su/$', m_views.search_user_extended),
    #url(r'^mdc/$', s_views.mdc),
]

handler404 = views.error_404
handler500 = views.error_500
admin.site.site_header = "TNP Admin Portal"
admin.site.site_title = "TNP Admin Portal"
admin.site.index_title = "Welcome to TNP Admin Portal"

student/forms.py
from django import forms
from .models import *
from management import models as m_models
from django.core.validators import RegexValidator
from django.template.defaultfilters import filesizeformat
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

custom_validator = RegexValidator(r'^[-\w\s+]*$', 'Only alphanumeric characters including space and hyphen are allowed')
mobile_number_validator = RegexValidator(r'^[0-9]{10}$', 'Only 10 digit number is accepteable.')

gender_choice = (
    ('male','Male'),
    ('female','Female')
    )

category_choice = (
    ('general','General'),
    ('obc','OBC'),
    ('sc','SC'),
    ('st','ST')
    )

class student_activate_form(forms.Form):
    rollno = forms.CharField(required = True,max_length=11,widget=forms.TextInput(attrs={'class':'validate','data-length':'11'}))

#This py file developed by Yash Kulshreshtha
#visit https://fb.com/yksmbkkr

class forgot_passoword_form(forms.Form):
    username = forms.CharField(required = True, max_length=20)

class student_profile_form(forms.ModelForm):
    f_name = forms.CharField(label='First Name',required = True,max_length=50,widget=forms.TextInput(attrs={'class':'validate'}))
    l_name = forms.CharField(label='Last Name',required = True,max_length=50,widget=forms.TextInput(attrs={'class':'validate'}))
    father = forms.CharField(label="Father's Name",required = True,max_length=50,widget=forms.TextInput(attrs={'class':'validate'}))
    mother = forms.CharField(label="Mother's Name",required = True,max_length=50,widget=forms.TextInput(attrs={'class':'validate'}))
    address = forms.CharField(label="Correspondence Address",required = True, widget = forms.Textarea(attrs = {'class':'materialize-textarea'}))
    mobile = forms.CharField(label="Mobile Number",validators=[mobile_number_validator], required = True, max_length=10,min_length=10, widget = forms.TextInput(attrs={'class':'validate', 'pattern':'[0-9]{10}','title':'10 digit mobile number only'}))
    branch = forms.ModelChoiceField(queryset = m_models.branches.objects.all(), empty_label = 'Select Branch', required = True)
    #be_marks = forms.DecimalField(max_digits=5,decimal_places=2,required = True,widget = forms.TextInput(attrs = {'class':'validate'}))
    marks_12 = forms.DecimalField(label="XII Percentage",max_digits=5,decimal_places=2,required = True,widget = forms.TextInput(attrs = {'class':'validate'}))
    marks_11 = forms.DecimalField(label="X Percentage",max_digits=5,decimal_places=2,required = True,widget = forms.TextInput(attrs = {'class':'validate'}))
    gender = forms.ChoiceField(choices = gender_choice, required = True)
    father_occupation = forms.CharField(label="Father's Occupation",required = True,max_length=150,widget=forms.TextInput(attrs={'class':'validate'}))
    mother_occupation = forms.CharField(label="Mother's Occupation", required = True,max_length=150,widget=forms.TextInput(attrs={'class':'validate'}))
    alternate_mobile = forms.CharField(label="Alternate Mobile Number",validators=[mobile_number_validator], required = True, max_length=10,min_length=10, widget = forms.TextInput(attrs={'class':'validate', 'pattern':'[0-9]{10}','title':'10 digit mobile number only'}))
    # backlogs = forms.DecimalField(max_digits=5,decimal_places=2,required = True,widget = forms.TextInput(attrs = {'class':'validate'}))
    intern_company = forms.CharField(label="Company You have Interned With (Name only)",required = True,max_length=200,widget=forms.TextInput(attrs={'class':'validate'}))
    permanent_address = forms.CharField(label="Permanent Address",required = True, widget = forms.Textarea(attrs = {'class':'materialize-textarea'}))
    category = forms.ChoiceField(choices = category_choice, required = True)
    passing_year_10 = forms.IntegerField(label="X Passing Year",required = True, widget = forms.TextInput(attrs = {'class':'validate', 'pattern':'[0-9]{4}','title':'4 digit year only'}))
    passing_year_12 = forms.IntegerField(label="XII Passing Year",required = True, widget = forms.TextInput(attrs = {'class':'validate', 'pattern':'[0-9]{4}','title':'4 digit year only'}))


    class Meta:
        model = student_profile
        fields = (
            'f_name',
            'l_name',
            'branch',
            'intern_company',
            'father',
            'father_occupation',
            'mother',
            'mother_occupation',
            'address',
            'permanent_address',
            'mobile',
            'alternate_mobile',
            'marks_11',
            'passing_year_10',
            'marks_12',
            'passing_year_12',
            'gender',
            'category',
            )

class home_search_form(forms.Form):
    slug = forms.CharField(validators=[custom_validator], required = True, max_length=20, widget = forms.TextInput(attrs={'class':'form-control'}))

class resume_drive_form(forms.ModelForm):
    resume1 = forms.FileField()
    resume2 = forms.FileField(required = False)
    resume3 = forms.FileField(required = False)
    
    def clean_resume1(self):
            resume1 = self.cleaned_data['resume1']
            if resume1:
                if '.com' in resume1.name:
                    raise forms.ValidationError(_('Unable to save : File name should not contain ".com"'),
                                                code='InvalidFileName', )
            try:
                content_type = resume1.content_type.split('/')[1]
                if content_type in settings.CONTENT_TYPES_PDF:
                    if resume1._size > settings.MAX_UPLOAD_SIZE:
                        raise forms.ValidationError(_('Please keep filesize under %(permitsize)s. Current filesize %(thissize)s'), code='InvalidFileSize', params ={'permitsize' : filesizeformat(settings.MAX_UPLOAD_SIZE), 'thissize':filesizeformat(resume1._size)},)
                else:
                    raise forms.ValidationError(_('File type is not supported. Only PDF supported.'), code = 'InvalidFileType',)
            except AttributeError:
                pass
            return resume1
    def clean_resume2(self):
            resume2 = self.cleaned_data['resume2']
            if resume2:
                if '.com' in resume2.name:
                    raise forms.ValidationError(_('Unable to save : File name should not contain ".com"'),
                                                code='InvalidFileName', )
            try:
                content_type = resume2.content_type.split('/')[1]
                if content_type in settings.CONTENT_TYPES_PDF:
                    if resume2._size > settings.MAX_UPLOAD_SIZE:
                        raise forms.ValidationError(_('Please keep filesize under %(permitsize)s. Current filesize %(thissize)s'), code='InvalidFileSize', params ={'permitsize' : filesizeformat(settings.MAX_UPLOAD_SIZE), 'thissize':filesizeformat(resume2._size)},)
                else:
                    raise forms.ValidationError(_('File type is not supported. Only PDF supported.'), code = 'InvalidFileType',)
            except AttributeError:
                pass
            return resume2
    def clean_resume3(self):
            resume3 = self.cleaned_data['resume3']
            if resume3:
                if '.com' in resume3.name:
                    raise forms.ValidationError(_('Unable to save : File name should not contain ".com"'),
                                                code='InvalidFileName', )
            try:
                content_type = resume3.content_type.split('/')[1]
                if content_type in settings.CONTENT_TYPES_PDF:
                    if resume3._size > settings.MAX_UPLOAD_SIZE:
                        raise forms.ValidationError(_('Please keep filesize under %(permitsize)s. Current filesize %(thissize)s'), code='InvalidFileSize', params ={'permitsize' : filesizeformat(settings.MAX_UPLOAD_SIZE), 'thissize':filesizeformat(resume3._size)},)
                else:
                    raise forms.ValidationError(_('File type is not supported. Only PDF supported.'), code = 'InvalidFileType',)
            except AttributeError:
                pass
            return resume3
    class Meta:
        model = resume_drive
        fields = {
            'resume1',
            'resume2',
            'resume3',
            }


class student_profile_edit_form(forms.ModelForm):
    f_name = forms.CharField(label='First Name',required = True,max_length=50,widget=forms.TextInput(attrs={'class':'validate'}))
    l_name = forms.CharField(label='Last Name',required = True,max_length=50,widget=forms.TextInput(attrs={'class':'validate'}))
    father = forms.CharField(label="Father's Name",required = True,max_length=50,widget=forms.TextInput(attrs={'class':'validate'}))
    mother = forms.CharField(label="Mother's Name",required = True,max_length=50,widget=forms.TextInput(attrs={'class':'validate'}))
    address = forms.CharField(label="Correspondence Address",required = True, widget = forms.Textarea(attrs = {'class':'materialize-textarea'}))
    mobile = forms.CharField(label="Mobile Number",validators=[mobile_number_validator], required = True, max_length=10,min_length=10, widget = forms.TextInput(attrs={'class':'validate', 'pattern':'[0-9]{10}','title':'10 digit mobile number only'}))
    #be_marks = forms.DecimalField(max_digits=5,decimal_places=2,required = True,widget = forms.TextInput(attrs = {'class':'validate'}))
    marks_12 = forms.DecimalField(label="XII Percentage",max_digits=5,decimal_places=2,required = True,widget = forms.TextInput(attrs = {'class':'validate'}))
    marks_11 = forms.DecimalField(label="X Percentage",max_digits=5,decimal_places=2,required = True,widget = forms.TextInput(attrs = {'class':'validate'}))
    gender = forms.ChoiceField(choices = gender_choice, required = True)
    father_occupation = forms.CharField(label="Father's Occupation",required = True,max_length=150,widget=forms.TextInput(attrs={'class':'validate'}))

student/templates/mdc.html
{%load static%}
{% load app_filters%}
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
   {%include 's_head.html'%}
    {%block head%}
    {%endblock%}
</head>
<body style="background-image:url({%static 'bg.jpg'%}); background-size:cover; background-attachment: fixed;">
    <header>
      <div class="navbar-fixed">
          <ul id="why-nsit-dropdown" class="dropdown-content">
                <li><a href="{%url 'student:history_s'%}">History</a></li>
                <li><a href="{%url 'student:students_s'%}">Student</a></li>
                <li><a href="{%url 'student:faculty_s'%}">Faculty &amp; Research</a></li>
                <li><a href="{%url 'student:alumni_s'%}">Alumni</a></li>
                <li><a href="{%url 'student:courses_s'%}">Courses Offered</a></li>
           </ul>
          <ul id="why-nsit-dropdown-m" class="dropdown-content">
               <li><a href="{%url 'student:history_s'%}">History</a></li>
                <li><a href="{%url 'student:students_s'%}">Student</a></li>
                <li><a href="{%url 'student:faculty_s'%}">Faculty &amp; Research</a></li>
                <li><a href="{%url 'student:alumni_s'%}">Alumni</a></li>
                <li><a href="{%url 'student:courses_s'%}">Courses Offered</a></li>
           </ul>
          <ul id="placement-dropdown" class="dropdown-content">
                <li><a href="{%url 'student:procedure_s'%}">Procedure</a></li>
                <li><a href="{%url 'student:policy_s'%}">Policy</a></li>
           </ul>
          <ul id="placement-dropdown-m" class="dropdown-content">
                <li><a href="{%url 'student:procedure_s'%}">Procedure</a></li>
                <li><a href="{%url 'student:policy_s'%}">Policy</a></li>
           </ul>
          {%if user.is_authenticated%}
          <ul id="account-dropdown" class="dropdown-content">
                <li><a href="{%url 'student:s_home'%}">Apply</a></li>
                <li><a href="{%url 'student:my_reg'%}">My Registrations</a></li>
                <li><a href="{%url 'student:s_resume'%}">Resume Drive</a></li>
                <li><a href="{%url 'student:s_profile'%}">Profile</a></li>
                <li><a href="{%url 'student:s_change_pass'%}">Change Password</a></li>
           </ul>
          {%endif%}
           <nav class="cyan darken-4" role="navigation">
                <div class="nav-wrapper container"><div id="logo-container" class="brand-logo">
                {%if user.is_authenticated%}
                    {{user|get_top_placement}}
                {% else %}
                    TNP Portal
                {% endif%}
                 </div>
                    <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                    <ul class="right hide-on-med-and-down">
                        {%if user.managers%}
                        <li><a href="{%url 'management:m_home'%}">Management Dashboard</a></li>
                        {%endif%}
                        <li><a href="{%url 'student:all_home'%}">Home</a></li>
                        <li><a class="dropdown-trigger" href="#!" data-target="why-nsit-dropdown">Why NSIT<i class="material-icons right">arrow_drop_down</i></a></li>
                        <li><a class="dropdown-trigger" href="#!" data-target="placement-dropdown">Placement<i class="material-icons right">arrow_drop_down</i></a></li>
                        {%if user.is_authenticated%}
                        <li><a class="dropdown-trigger" href="#!" data-target="account-dropdown">Account<i class="material-icons right">arrow_drop_down</i></a></li>
                        <li><a href="{%url 'student:s_logout'%}">Logout</a></li>
                        {%else%}
                         <li><a href="{%url 'student:s_activation'%}">Activate</a></li>
                        <li><a href="{%url 'student:s_login'%}">Login</a></li>
                        <li><a href="{%url 'student:contact_us'%}">Contact Us</a></li>
                        {%endif%}
                    </ul>      
                </div>
            </nav>
        </div>
    <ul id="nav-mobile" class="sidenav">
                        {%if user.managers%}
                        <li><a href="{%url 'management:m_home'%}">Management Dashboard</a></li>
                        {%endif%}
            <li><a href="{%url 'student:all_home'%}">Home</a></li>
        <li><a class="dropdown-trigger" href="#!" data-target="why-nsit-dropdown-m">Why NSIT<i class="material-icons right">arrow_drop_down</i></a></li>
         <li><a class="dropdown-trigger" href="#!" data-target="placement-dropdown-m">Placement<i class="material-icons right">arrow_drop_down</i></a></li>
                       
         {%if user.is_authenticated%}
            <li><a href="{%url 'student:s_home'%}">Apply</a></li>
            <li><a href="{%url 'student:my_reg'%}">My Registrations</a></li>
            <li><a href="{%url 'student:s_profile'%}">Profile</a></li>
            <li><a href="{%url 'student:s_resume'%}">Resume Drive</a></li>
            <li><a href="{%url 'student:s_change_pass'%}">Change Password</a></li>
            <li><a href="{%url 'student:s_logout'%}">Logout</a></li>
        {%else%}
            <li><a href="{%url 'student:s_activation'%}">Activate</a></li>
            <li><a href="{%url 'student:s_login'%}">Login</a></li>
        <li><a href="{%url 'student:contact_us'%}">Contact Us</a></li>
         {%endif%}
      </ul>
        </header>
    <main>
    {%block body%}
    
    <div class="container">
        <div class="section">
            <div class="row  section-form">
                <div class="col m6 offset-m3 s12 center-align">
                    <div class="card card-panel">
                        <div class="card-content">
                            <div class="card-title"><h4 class="center-align cyan-text text-darken-4">Activate</h4></div>
                            <div class="row">
                                <form class="col s12">
                                    <div class="input-field col s12">
                                        <input id="last_name" type="text" class="validate">
                                        <label for="last_name">Last Name</label>
                                    </div>
                                    <div class="input-field col s12">
                                        <select>
  <option value="" disabled selected>Select Branch</option>

  <option value="1">BT</option>

  <option value="2">ECE</option>

  <option value="3">ICE</option>

  <option value="4">IT</option>

  <option value="5">COE</option>

  <option value="6">ME</option>

  <option value="7">MPAE</option>

</select>
                                      <!--  <input id="last_name" type="text" class="validate"> -->
                                        
                                    </div>
                                    <div class="col s12">
                                       
                                    </div>
                                </form>
                            </div>

                        </div>
                        <div class="card-action">
                            <div class="row">
                                <div class="col s12 l6 pad-top" >
                                    <button class=" col s12 btn waves-effect waves-light z-depth-4">Login</button>
                                </div>
                                <div class="col s12 l6 pad-top">
                                    <button class=" col s12 btn waves-effect waves-light z-depth-4">Forgot Password</button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>

    {%endblock%}
        </main>
  <footer class="page-footer teal darken-4" style="padding-top:2px !important;">
      <div class="container">
          <div class="row" style="margin-bottom:1px !important;">
              <div class="col s12">
                  <p class="center-align p-mar">&copy; 2018 Copyright | Created by <a href="https://www.linkedin.com/in/ankitagarwal6899"><u><b>Ankit Agarwal</b></u></a> &amp; <a href="https://www.linkedin.com/in/yksmbkkr"><u><b>Yash Kulshreshtha</b></u></a></p>
              </div>
          </div>
      </div>
    
  </footer>


    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.2/aos.js"></script>
    <script src="{%static 's_js/init.js'%}"></script>
    <script>
        AOS.init({
            duration: 1200,
            })
    </script>
    {%block scripts%}
    {%endblock%}
</body>
</html>

student/templates/password_reset_form.html
{% extends 'skeleton.html' %}

{% block body %}
  <h3>Forgot password</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button> 
  </form>
{% endblock %}

student/templates/s_activation.html
{%extends 'mdc.html'%}
{%load static%}


{%block body%}

<div class="container">
        <div class="section">
            <div class="row  section-form">
                {%include 's_err_msg.html'%}
                <div class="col m6 offset-m3 s12 center-align">
                    <div class="card card-panel">
                        <div class="card-content">
                            <div class="card-title"><h4 class="center-align cyan-text text-darken-4">Activate</h4></div>
                            <div class="row">
                                <form class="col s12" method="post" action="">
                                    <div class="input-field col s12">
                                        {{form.rollno}}
                                      <!--  <input id="last_name" type="text" class="validate"> -->
                                        <label for="id_rollno">Roll Number</label>
                                    </div>
                                    {%csrf_token%}
                                    <div class="col s12">
                                        <button class=" col s12 btn waves-effect waves-light z-depth-4" type="submit">Submit</button>
                                    </div>
                                </form>
                            </div>

                        </div>
                        <div class="card-action">
                            <div class="row">
                                <div class="col s12 l6 pad-top" >
                                    <a href="{%url 'student:s_login'%}" class=" col s12 btn waves-effect waves-light z-depth-4">Login</a>
                                </div>
                                <div class="col s12 l6 pad-top">
                                    <a href="{%url 'student:s_forgot_pass'%}" class=" col s12 btn waves-effect waves-light z-depth-4">Forgot Password</a>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

{%endblock%}

student/templates/s_err_msg.html
{%load static%}
{%if messages%}
{%autoescape off%}
<div class="col m6 offset-m3 s12 center-align">
      {%for message in messages%}
                    <div id="card-alert" class="card {{message.tags}}">
                        <div class="card-content white-text">
                            <p>{{message}}</p>
                        </div>
                    </div>
     {%endfor%}
                </div>
{%endautoescape%}
{%endif%}
{%if form.errors%}

<div class="col m6 offset-m3 s12 center-align">
                    <div id="card-alert" class="card red">
                        <div class="card-content white-text">
                            {%for field in form%}
                            <ul>
    {%for error in field.errors%}
    <li>{{field.name}} : {{error}}</li> 
    {%endfor%}
</ul>
                            {%endfor%}
                        </div>
                    </div>
                </div>


{%endif%}